# Configuration for header generation.

# This file is part of Cantera. See License.txt in the top-level directory or
# at https://cantera.org/license.txt for license and copyright information.

# List of files to ignore entirely. For the header generator, this option is only used
# for testing or debugging purposes and should otherwise be left empty.
ignore_files: []

# Dictionary of file names and list of functions to ignore. For the header generator,
# this option is only used for testing or debugging purposes and should otherwise be
# left empty.
ignore_funcs: {}

# Return type crosswalks
ret_type_crosswalk:
  bool: int32_t
  void: int32_t
  int: int32_t
  size_t: int32_t
  shared_ptr<T>: int32_t
  double: double
  string: char*
  double*: double*
  const double*: double*
  vector<double>: double*
  span<double>: double*
  span<const double>: const double*

# Parameter type crosswalks
par_type_crosswalk:
  bool: int32_t
  int: int32_t
  size_t: int32_t
  shared_ptr<T>: int32_t
  int*: int32_t*
  vector<int>: int32_t*
  vector<shared_ptr<T>>: int32_t*
  span<shared_ptr<T>>: int32_t*
  double: double
  double*: double*
  vector<double>: double*
  string: char*
  span<double>: double*
  span<const double>: const double*
