version: 1.0.{build}
install:
- ps: |
    C:\Python37-x64\python.exe -m pip install --no-cache-dir --upgrade pip
    C:\Python37-x64\python.exe -m pip install --upgrade setuptools
    C:\Python37-x64\python.exe -m pip install --upgrade --no-warn-script-location wheel
    C:\Python37-x64\Scripts\pip.exe install scons
    C:\Python37-x64\Scripts\pip.exe install --no-cache-dir --no-warn-script-location numpy
    C:\Python37-x64\Scripts\pip.exe install --no-warn-script-location cython
    C:\Python37-x64\Scripts\pip.exe install pypiwin32

build_script:
- cmd: C:\Python37-x64\Scripts\scons build -j2 boost_inc_dir=C:\Libraries\boost_1_62_0 debug=n VERBOSE=y python_package=full

test_script:
- ps: |
    C:\Python37-x64\Scripts\scons test
    $sconsstatus = $lastexitcode
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\work\gtest-general.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\work\gtest-thermo.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\work\gtest-equil.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\work\gtest-kinetics.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\work\gtest-transport.xml))
    if ( $sconsstatus ) { exit $sconsstatus }
