# Configuration for YAML output.

# This file is part of Cantera. See License.txt in the top-level directory or
# at https://cantera.org/license.txt for license and copyright information.

# Ignore these files entirely:
ignore_files:
- ctrdiag_auto.yaml  # for testing purposes

# Ignore these specific functions:
ignore_funcs: {}
